# Generated by Django 6.0.4 on 2026-04-22 19:38

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('is_stuck', models.BooleanField(default=False)),
                ('stuck_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('onboarding_status', models.CharField(choices=[('REQUEST', 'ON BOARD REQUEST'), ('REVIEW', 'UNDER REVIEW'), ('REJECTED', 'APPLICATION REJECTED'), ('ACTIVATED', 'MERCHANT ACTIVATED')], default='REQUEST', max_length=20)),
                ('last_active', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('UPLOADED', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('requirement_type', models.CharField(choices=[('ID', 'NATIONAL ID'), ('LICENCE', 'TRADING LICENCE'), ('PHOTO', 'PASSPORT SIZED PHOTO')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='activation_tracker_app.merchant')),
            ],
        ),
    ]
