ONBOARDING_STATUS_CHOICES = (
        ('REQUEST', 'ON BOARD REQUEST'),
        ('REVIEW', 'UNDER REVIEW'),
        ('REJECTED', 'APPLICATION REJECTED'),
        ('ACTIVATED', 'MERCHANT ACTIVATED'),
    )